version: "2"
services:

  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - 1411:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Secret1234
    volumes:
      - ./dati/mssql/data:/var/opt/mssql/data
      - ./sql/mssql/:/var/opt/mssql/init/

    command: /bin/bash /var/opt/mssql/init/entrypoint.sh
  backend:
    container_name: osamard-be
    build:
      dockerfile: Dockerfile
    ports:
      - 8011:8080
    volumes:
      - ./dati/be:/var